// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVdTAEoODIUeYW4My5vxp03AowO-ie39g',
    appId: '1:383674267703:web:021c7961ad112c38d2a7b2',
    messagingSenderId: '383674267703',
    projectId: 'fluttervideocall-c02a4',
    authDomain: 'fluttervideocall-c02a4.firebaseapp.com',
    databaseURL: 'https://fluttervideocall-c02a4-default-rtdb.firebaseio.com',
    storageBucket: 'fluttervideocall-c02a4.appspot.com',
    measurementId: 'G-YGX24NT5KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbB_k9rvDUxciQw6YvqeQUgjO5VZZF4xI',
    appId: '1:383674267703:android:c7793aa6d121e3e2d2a7b2',
    messagingSenderId: '383674267703',
    projectId: 'fluttervideocall-c02a4',
    databaseURL: 'https://fluttervideocall-c02a4-default-rtdb.firebaseio.com',
    storageBucket: 'fluttervideocall-c02a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLSGpWvGD1lt0zte3UkXTmIco5Azvzqyo',
    appId: '1:383674267703:ios:bf199631c117bf5fd2a7b2',
    messagingSenderId: '383674267703',
    projectId: 'fluttervideocall-c02a4',
    databaseURL: 'https://fluttervideocall-c02a4-default-rtdb.firebaseio.com',
    storageBucket: 'fluttervideocall-c02a4.appspot.com',
    androidClientId: '383674267703-55um6anve6ktu8phab62av1kv4ohp49d.apps.googleusercontent.com',
    iosClientId: '383674267703-j9bm3vb83it25gl6v3277hqsdkth76kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVideoCallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLSGpWvGD1lt0zte3UkXTmIco5Azvzqyo',
    appId: '1:383674267703:ios:bf199631c117bf5fd2a7b2',
    messagingSenderId: '383674267703',
    projectId: 'fluttervideocall-c02a4',
    databaseURL: 'https://fluttervideocall-c02a4-default-rtdb.firebaseio.com',
    storageBucket: 'fluttervideocall-c02a4.appspot.com',
    androidClientId: '383674267703-55um6anve6ktu8phab62av1kv4ohp49d.apps.googleusercontent.com',
    iosClientId: '383674267703-j9bm3vb83it25gl6v3277hqsdkth76kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVideoCallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVdTAEoODIUeYW4My5vxp03AowO-ie39g',
    appId: '1:383674267703:web:210dbc2a6cdb34e3d2a7b2',
    messagingSenderId: '383674267703',
    projectId: 'fluttervideocall-c02a4',
    authDomain: 'fluttervideocall-c02a4.firebaseapp.com',
    databaseURL: 'https://fluttervideocall-c02a4-default-rtdb.firebaseio.com',
    storageBucket: 'fluttervideocall-c02a4.appspot.com',
    measurementId: 'G-NR9PD1Z0NC',
  );
}
